"""Google Ads optimization models.

Stores recommendations and executed optimization actions for automated Google Ads campaign management.
"""
import uuid
from datetime import datetime
from decimal import Decimal
from typing import Optional

from sqlalchemy import DateTime, ForeignKey, Numeric, String, Text, UniqueConstraint, Boolean
from sqlalchemy.dialects.postgresql import JSONB, UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base, TenantMixin, TimestampMixin


class GoogleAdsOptimizationRecommendation(Base, TenantMixin, TimestampMixin):
    """Optimization recommendation generated by recommendation engine."""

    __tablename__ = "google_ads_optimization_recommendations"
    __table_args__ = (
        UniqueConstraint(
            "tenant_id",
            "campaign_id",
            "recommendation_type",
            "entity_id",
            "entity_type",
            "recommendation_date",
            name="uq_optimization_recommendation",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True), ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False, index=True
    )
    campaign_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True), ForeignKey("pipeboard_campaigns.id", ondelete="CASCADE"), nullable=False, index=True
    )

    # Recommendation metadata
    recommendation_date: Mapped[str] = mapped_column(String(10), nullable=False, index=True)  # YYYY-MM-DD
    recommendation_type: Mapped[str] = mapped_column(String(50), nullable=False)  # pause_keyword, scale_bid, etc
    status: Mapped[str] = mapped_column(String(50), nullable=False, default="pending")  # pending / executed / skipped

    # Entity being optimized
    entity_type: Mapped[str] = mapped_column(String(50), nullable=False)  # keyword / ad_group / geo / device
    entity_id: Mapped[str] = mapped_column(String(255), nullable=False, index=True)  # platform-specific ID
    entity_name: Mapped[Optional[str]] = mapped_column(String(500))

    # Recommendation details (action-specific params)
    recommendation_data: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)

    # Metrics that triggered recommendation
    metric_data: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)

    # Confidence and reasoning
    confidence_score: Mapped[Optional[Decimal]] = mapped_column(Numeric(3, 2))  # 0.00 to 1.00
    reasoning: Mapped[Optional[str]] = mapped_column(Text)

    executed_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))


class GoogleAdsOptimizationAction(Base, TenantMixin, TimestampMixin):
    """Executed optimization action (audit trail)."""

    __tablename__ = "google_ads_optimization_actions"

    id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True), ForeignKey("tenants.id", ondelete="CASCADE"), nullable=False, index=True
    )
    recommendation_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        PGUUID(as_uuid=True), ForeignKey("google_ads_optimization_recommendations.id", ondelete="SET NULL"),
        nullable=True, index=True
    )
    campaign_id: Mapped[uuid.UUID] = mapped_column(
        PGUUID(as_uuid=True), ForeignKey("pipeboard_campaigns.id", ondelete="CASCADE"), nullable=False, index=True
    )

    # Action details
    action_type: Mapped[str] = mapped_column(String(50), nullable=False)  # pause_keyword, increase_bid, etc
    entity_type: Mapped[str] = mapped_column(String(50), nullable=False)  # keyword / ad_group / geo / device
    entity_id: Mapped[str] = mapped_column(String(255), nullable=False, index=True)

    # Request/Response
    request_data: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    response_data: Mapped[Optional[dict]] = mapped_column(JSONB)

    # Status tracking
    status: Mapped[str] = mapped_column(String(50), nullable=False, default="pending")  # pending / success / failed
    error_message: Mapped[Optional[str]] = mapped_column(Text)

    # Execution timing
    action_date: Mapped[str] = mapped_column(String(10), nullable=False, index=True)  # YYYY-MM-DD
    executed_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))

    # Impact tracking (populated after metrics update)
    metrics_before: Mapped[Optional[dict]] = mapped_column(JSONB)
    metrics_after: Mapped[Optional[dict]] = mapped_column(JSONB)
    impact_assessed_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True))
