"""Competitor intelligence service for AI Marketing.

Data sources (real only — no fabrication, per CLAUDE.md):
  - Google Places API (New): nearby restaurants, ratings, review counts, price
    level, website presence, coordinates.

Places exposes NO advertising data (Google/Meta/LinkedIn ads, landing pages,
promotions). Those fields are surfaced as AI-inferred strategy (clearly labeled
with confidence + explanation) rather than presented as measured facts.

Threat / Opportunity scores are computed deterministically from real Places
metrics. The qualitative summaries + suggested campaign + headlines + monthly
opportunity estimate are generated by Claude and always carry a confidence
score and an explanation of assumptions.
"""
import json
import math
from dataclasses import dataclass, field
from typing import Any

import anthropic
import structlog

from app.core.config import settings

logger = structlog.get_logger(__name__)

_MODEL = "claude-sonnet-4-6"

# Approximate metres per degree latitude (good enough for a 5 km ranking radius).
_M_PER_DEG_LAT = 111_320.0


@dataclass
class Competitor:
    place_id: str
    name: str | None
    address: str | None
    rating: float | None
    review_count: int
    price_level: str | None
    website: str | None
    primary_type: str | None
    distance_m: float | None
    threat_score: int
    opportunity_score: int


@dataclass
class CompetitorIntel:
    location_name: str | None
    own_rating: float | None
    own_review_count: int
    radius_km: float
    competitor_count: int
    threat_score: int  # market-level, 0-100
    opportunity_score: int  # market-level, 0-100
    competitors: list[Competitor] = field(default_factory=list)
    advertising_summary: str = ""
    promotion_summary: str = ""
    suggested_campaign: str = ""
    suggested_headlines: list[str] = field(default_factory=list)
    estimated_monthly_opportunity: str = ""
    ai_confidence: float = 0.0
    ai_explanation: str = ""
    ai_available: bool = False


def _haversine_m(lat1: float, lng1: float, lat2: float, lng2: float) -> float:
    r = 6_371_000.0
    p1, p2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dl = math.radians(lng2 - lng1)
    a = math.sin(dphi / 2) ** 2 + math.cos(p1) * math.cos(p2) * math.sin(dl / 2) ** 2
    return 2 * r * math.asin(math.sqrt(a))


def _clamp(v: float) -> int:
    return max(0, min(100, round(v)))


def _score_competitor(
    comp_rating: float | None,
    comp_reviews: int,
    own_rating: float | None,
    own_reviews: int,
    distance_m: float | None,
    radius_m: float,
) -> tuple[int, int]:
    """Deterministic Threat + Opportunity scores (0-100) from real Places metrics.

    Threat  — how strongly this competitor beats us: higher rating, more review
              volume (popularity proxy), closer proximity all raise it.
    Opportunity — how much of their demand we could realistically win: popular
              competitors (high review volume) whose rating trails ours are the
              softest targets.
    """
    o_rating = own_rating if own_rating is not None else 4.0
    c_rating = comp_rating if comp_rating is not None else o_rating

    # Rating advantage for the competitor, scaled to +/-1.
    rating_gap = (c_rating - o_rating) / 5.0

    # Volume advantage, log-scaled so a giant chain doesn't peg the scale.
    c_vol = math.log10(comp_reviews + 1)
    o_vol = math.log10(own_reviews + 1)
    vol_gap = c_vol - o_vol  # positive => they have more reviews than us

    # Proximity factor: 1.0 at our doorstep, ~0 at the radius edge.
    prox = 1.0
    if distance_m is not None and radius_m > 0:
        prox = max(0.0, 1.0 - distance_m / radius_m)

    threat = 50 + 60 * rating_gap + 18 * vol_gap
    threat += 8 * (prox - 0.5)

    # Opportunity: their popularity is the prize, their rating weakness is the opening.
    weakness = (o_rating - c_rating) / 5.0  # positive => we out-rate them
    popularity = min(1.0, c_vol / 3.0)  # ~1000 reviews saturates
    opportunity = 35 + 45 * weakness + 25 * popularity
    opportunity += 5 * (prox - 0.5)

    return _clamp(threat), _clamp(opportunity)


def build_intel(
    own: dict[str, Any],
    nearby: list[dict[str, Any]],
    radius_km: float,
) -> CompetitorIntel:
    """Assemble deterministic competitor intel from real Places data."""
    radius_m = radius_km * 1000.0
    own_rating = own.get("rating")
    own_reviews = int(own.get("user_rating_count") or 0)
    own_id = own.get("place_id")
    own_lat, own_lng = own.get("lat"), own.get("lng")

    competitors: list[Competitor] = []
    for c in nearby:
        if c["id"] == own_id:
            continue  # never rank ourselves
        c_reviews = int(c.get("user_rating_count") or 0)
        dist = None
        if own_lat is not None and c.get("lat") is not None:
            dist = _haversine_m(own_lat, own_lng, c["lat"], c["lng"])
            if dist > radius_m:
                continue
        threat, opp = _score_competitor(
            c.get("rating"), c_reviews, own_rating, own_reviews, dist, radius_m
        )
        competitors.append(
            Competitor(
                place_id=c["id"],
                name=c.get("name"),
                address=c.get("address"),
                rating=c.get("rating"),
                review_count=c_reviews,
                price_level=c.get("price_level"),
                website=c.get("website"),
                primary_type=c.get("primary_type"),
                distance_m=round(dist) if dist is not None else None,
                threat_score=threat,
                opportunity_score=opp,
            )
        )

    competitors.sort(key=lambda x: x.threat_score, reverse=True)

    market_threat = _clamp(
        sum(c.threat_score for c in competitors) / len(competitors)
    ) if competitors else 0
    market_opp = _clamp(
        max((c.opportunity_score for c in competitors), default=0) * 0.6
        + (sum(c.opportunity_score for c in competitors) / len(competitors) * 0.4 if competitors else 0)
    )

    return CompetitorIntel(
        location_name=own.get("name"),
        own_rating=own_rating,
        own_review_count=own_reviews,
        radius_km=radius_km,
        competitor_count=len(competitors),
        threat_score=market_threat,
        opportunity_score=market_opp,
        competitors=competitors,
    )


_SYSTEM_PROMPT = """You are a restaurant marketing strategist analyzing a local competitive set.

You are given a target restaurant and its nearby competitors. The ONLY hard data
available is Google Places data: name, rating, review count, price level, and
whether the competitor has a website. You do NOT have their ad spend, ad creatives,
landing pages, or promotions.

Produce a concise executive briefing. Where you infer advertising or promotion
behaviour, say plainly it is inferred from public signals (website presence,
review velocity, price positioning) and not measured ad data. Never invent
specific dollar ad-spend numbers or fake campaign IDs.

Respond ONLY with valid JSON:
{
  "advertising_summary": "2-3 sentences on the likely paid-media posture of the set (inferred).",
  "promotion_summary": "2-3 sentences on likely promotions/offers positioning (inferred).",
  "suggested_campaign": "one concrete campaign concept for the target restaurant.",
  "suggested_headlines": ["6 Google Ads headlines, each <=30 chars"],
  "estimated_monthly_opportunity": "a conservative revenue-opportunity RANGE as a string, e.g. \\"$3,000-$6,000/mo\\", with the basis stated in the explanation.",
  "confidence_score": 0.0-1.0,
  "explanation": "how you reached the estimate and what assumptions/limitations apply."
}"""


def synthesize(intel: CompetitorIntel) -> None:
    """Fill the AI fields on `intel` in place via Claude. Best-effort; on any
    failure leaves ai_available=False so the UI shows a graceful fallback."""
    if not settings.ANTHROPIC_API_KEY:
        intel.ai_explanation = "ANTHROPIC_API_KEY not configured."
        return

    payload = {
        "target": {
            "name": intel.location_name,
            "rating": intel.own_rating,
            "review_count": intel.own_review_count,
        },
        "radius_km": intel.radius_km,
        "competitors": [
            {
                "name": c.name,
                "rating": c.rating,
                "review_count": c.review_count,
                "price_level": c.price_level,
                "has_website": bool(c.website),
                "distance_m": c.distance_m,
                "threat_score": c.threat_score,
                "opportunity_score": c.opportunity_score,
            }
            for c in intel.competitors[:15]
        ],
    }

    try:
        client = anthropic.Anthropic(api_key=settings.ANTHROPIC_API_KEY)
        resp = client.messages.create(
            model=_MODEL,
            max_tokens=1200,
            system=_SYSTEM_PROMPT,
            messages=[{"role": "user", "content": json.dumps(payload)}],
        )
        text = resp.content[0].text.strip()
        if text.startswith("```"):
            text = text.split("```")[1].removeprefix("json").strip()
        data = json.loads(text)
        intel.advertising_summary = str(data.get("advertising_summary", ""))
        intel.promotion_summary = str(data.get("promotion_summary", ""))
        intel.suggested_campaign = str(data.get("suggested_campaign", ""))
        headlines = data.get("suggested_headlines") or []
        intel.suggested_headlines = [str(h) for h in headlines][:6]
        intel.estimated_monthly_opportunity = str(data.get("estimated_monthly_opportunity", ""))
        intel.ai_confidence = float(data.get("confidence_score") or 0.0)
        intel.ai_explanation = str(data.get("explanation", ""))
        intel.ai_available = True
    except Exception as exc:  # noqa: BLE001 — best-effort AI layer
        logger.error("competitor_synthesis_failed", error=str(exc))
        intel.ai_available = False
        intel.ai_explanation = "AI synthesis unavailable right now."
